### ISSUE TITLE
Feature: referral program 

### ISSUE THREAD

**Issue by m7jalta** [Steffo99/greed#220] opened 2023-11-09 17:12 UTC
### Describe the proposed feature

1-referral program with customizable settings that allows the manager to change the % earning per deposit. 
for example the 'user 1' sent a link to the 'user 2', if a 'user 2' used a the refer link and deposit  $ the 'user 1' will earn %.

**Comment by Steffo99** [comment] 2023-11-09 17:24
Duplicate of #64.

**Closed by Steffo99** 2023-11-09 17:24 UTC
Labels: feature
