### ISSUE TITLE
Bug: Database is locked

### ISSUE THREAD

**Issue by laskriabdellah** [Steffo99/greed#213] opened 2023-10-05 01:03 UTC
### Describe the bug

Oct 03 23:49:44 roymail python[173741]: 2023-10-03 23:49:44 | Core | core | Received /start from: 841497496
Oct 03 23:49:49 roymail python[173741]: Exception in thread Worker 841497496:
Oct 03 23:49:49 roymail python[173741]: Traceback (most recent call last):
Oct 03 23:49:49 roymail python[173741]:   File "/srv/greed/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py",>
Oct 03 23:49:49 roymail python[173741]:     self.dialect.do_execute(
Oct 03 23:49:49 roymail python[173741]:   File "/srv/greed/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.p>
Oct 03 23:49:49 roymail python[173741]:     cursor.execute(statement, parameters)
Oct 03 23:49:49 roymail python[173741]: sqlite3.OperationalError: database is locked
Oct 03 23:49:49 roymail python[173741]: The above exception was the direct cause of the following exception:
Oct 03 23:49:49 roymail python[173741]: Traceback (most recent call last):
Oct 03 23:49:49 roymail python[173741]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Oct 03 23:49:49 roymail python[173741]:     self.run()
Oct 03 23:49:49 roymail python[173741]:   File "/srv/greed/worker.py", line 190, in run
Oct 03 23:49:49 roymail python[173741]:     self.session.commit()
Oct 03 23:49:49 roymail python[173741]:   File "/srv/greed/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py",>

**Comment by Steffo99** [comment] 2023-10-16 21:45
Sounds like a duplicate of #86; can you try the instructions there and post the debug logs?

**Closed by Steffo99** 2023-10-16 21:45 UTC
Labels: bug
