### ISSUE TITLE
Split products into multiple categories

### ISSUE THREAD

**Issue by DarrenWestwood** [Steffo99/greed#164] opened 2022-02-02 11:39 UTC
## Describe the feature
Split products into multiple categories (like electronics, clothes, food) instead of grouping them in a single catalog

## Reasoning for the implementation
Improves locating specific products and browsing products in larger stores with a wide range of products

## Additional information
Originally requested by users in another fork: https://github.com/DarrenWestwood/greed/issues/22

**Comment by Steffo99** [comment] 2022-02-02 13:46
Duplicate of #33 :)

**Closed by Steffo99** 2022-02-02 13:46 UTC
Labels: feature
