### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by jashvakharia** [Steffo99/greed#209] opened 2023-09-25 12:29 UTC
### Describe the proposed feature

i think you should add an option to sell files, like if i wanted to setup some kind of online store, selling files.....
it could help...

so what would happen is 
keep "thing" as the item
customer bought the amount of thing
once bought, those many files/lines get deleted from the source automatically so it doesnt go to the next customer, and it updates the stock automatically.

### Reasoning

wanted to make that kind of store.

**Comment by Steffo99** [comment] 2023-09-26 08:16
Duplicate of #166.

**Closed by Steffo99** 2023-09-26 08:16 UTC
Labels: feature
